### ISSUE TITLE
Conflicting dependencies are not resolved correctly

### ISSUE THREAD

**Issue by pditommaso** [puniverse/capsule-maven#1]
When downloading Maven dependencies the maven caplet may include multiple times the same artifact or resolve wrongly conflicting modules resulting in a broken classpath. 

The current dependency resolution strategy "first-listed-wins" is error prone, because it does not take in consideration that a higher version of the same dependency may be appear later in the dependencies tree. 

When a conflict arise the suggested approach is to pick the dependency with the latest version number as [discussed here](https://groups.google.com/forum/#!topic/capsule-user/MjtnvwtzSmI)

**Comment by pron** [comment]
I have not forgotten this issue -- it just turns out to be a bit trickier than I had thought. I have an idea how to fix it, though.

It turns out "last-version-wins" is already the strategy (it's Aether's default under some circumstances), but as Capsule makes several resolution requests to the Maven server (one for each manifest key), each is treated and resolved separately.

The solution is to combine all of those requests into one. It might take a bit, but I'll get around to it.

**Comment by pditommaso** [comment]
It sounds nice. This should make the resolution also faster! Shouldn't it?

p

**Comment by pron** [comment]
Hopefully, yes.

**Comment by pron** [comment]
Experimental fix. Can you try it now?
